### ISSUE TITLE
Allocations with CSI volume fail during Nomad agent restart

### ISSUE THREAD

**Issue by rbastiaans-tc** [hashicorp/nomad#13028]
### Nomad version

```Nomad v1.3.0 (52e95d64113e01be05d585d8b4c07f6f19efebbc)```

### Operating system and Environment details

Debian 10 Buster

### Issue

* Allocations using CSI volume will fail on client after Nomad agent restart
* while the CSI node and controller jobs stayed running and were unaffected by restart

### Reproduction steps

* Run CSI node/controller jobs as system job (on all nodes)
* Run Nomad job using CSI volume
* Restart nomad agent on client where Job with CSI volume runs by running:
  * `systemctl restart nomad`

#### Expected Result

* Allocation with CSI volume to stay running

#### Actual Result

* Allocation fails and is rescheduled

### Unit file

```
$ cat /lib/systemd/system/nomad.service
[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/
Wants=network-online.target
After=network-online.target
ConditionPathExists=/etc/nomad.d

# When using Nomad with Consul it is not necessary to start Consul first. These
# lines start Consul before Nomad as an optimization to avoid Nomad logging
# that Consul is unavailable at startup.
Wants=consul.service
After=consul.service

[Service]
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nomad agent -config /etc/nomad.d
KillMode=process
KillSignal=SIGINT
LimitNOFILE=infinity
LimitNPROC=infinity
Restart=on-failure
RestartSec=2
StartLimitBurst=3
StartLimitIntervalSec=10
TasksMax=infinity

[Install]
WantedBy=multi-user.target
```

### Job file (if appropriate)

CSI plugin:
```
$ cat cinder_csi.hcl 
job "cinder_csi" {
  datacenters = ["dc1"]
  type = "system"

  update {
    max_parallel = 1
    min_healthy_time = "10s"
  }

  group "node" {

    vault {
      policies = ["nomad_jobs_policy"]
    }

    task "node" {
      driver = "docker"

      config {
        image = "docker.io/k8scloudprovider/cinder-csi-plugin:v1.23.0"
        dns_servers = ["172.17.0.1"]
        privileged = true

        devices = [
          {
            host_path      = "/dev"
            container_path = "/dev"
          },
        ]

        args = [
          "/bin/cinder-csi-plugin",
          "--endpoint=unix:///csi/csi.sock",
          "--cloud-config=/local/cloud.conf",
          "--nodeid=$${node.unique.name}",
          "--cluster=$${NOMAD_DC}",
          "-v=4",
        ]
      }

      template {
        destination = "local/cloud.conf"
        change_mode = "restart"
        data = <<EOF
{{ with secret "secret/nomad_csi/xxx/xxxxx" -}}
[Global]
application-credential-name = xxx
application-credential-id = {{ .Data.id }}
application-credential-secret = {{ .Data.secret }}
auth-url = https://xxxx.xxxxx.xxxx/v3
region = xxxx
{{- end }}

[BlockStorage]
rescan-on-resize = true
ignore-volume-az = true
EOF
      }

      csi_plugin {
        id        = "cinder_csi_plugin"
        type      = "node"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }

  group "controller" {

    vault {
      policies = ["nomad_jobs_policy"]
    }

    task "controller" {
      driver = "docker"

      config {
        image = "docker.io/k8scloudprovider/cinder-csi-plugin:v1.23.0"
        dns_servers = ["172.17.0.1"]
        privileged = true

        args = [
          "/bin/cinder-csi-plugin",
          "--endpoint=unix:///csi/csi.sock",
          "--cloud-config=/local/cloud.conf",
          "--nodeid=$${node.unique.name}",
          "--cluster=$${NOMAD_DC}",
          "-v=4",
        ]
      }

      template {
        destination = "local/cloud.conf"
        change_mode = "restart"
        data = <<EOF
{{ with secret "secret/nomad_csi/xxxx/xxxxx" -}}
[Global]
application-credential-name = xxx
application-credential-id = {{ .Data.id }}
application-credential-secret = {{ .Data.secret }}
auth-url = https://xxxx.xxxxx.xxxxx/v3
region = xxxx
{{- end }}

[BlockStorage]
rescan-on-resize = true
ignore-volume-az = true
EOF
      }

      csi_plugin {
        id        = "cinder_csi_plugin"
        type      = "controller"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

CSI volume using job:
```
$ cat csitest.hcl 
job "csitest" {
  datacenters = ["dc1"]

  update {
    max_parallel = 1
    min_healthy_time = "10s"
    stagger = "30s"
  }

  group "csitest" {
    count = 3

    volume "csitest" {
      type = "csi"
      source = "csitest"
      attachment_mode = "file-system"
      access_mode = "single-node-writer"
      per_alloc = true
    }

    task "csitest" {
      driver = "docker"

      config {
        image = "python:3.7-alpine"
        entrypoint = ["sleep", "infinity"]
        dns_servers = ["172.17.0.1"]
      }

      volume_mount {
        volume = "csitest"
        destination = "/vol"
      }

      resources {
        memory = 128
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

```
Stopping Nomad...
==> Caught signal: interrupt
    2022-05-16T11:42:51.166Z [INFO]  agent: requesting shutdown
    2022-05-16T11:42:51.166Z [INFO]  client: shutting down
    2022-05-16T11:42:51.509Z [INFO]  client.plugin: shutting down plugin manager: plugin-type=device
    2022-05-16T11:42:51.509Z [INFO]  client.plugin: plugin manager finished: plugin-type=device
    2022-05-16T11:42:51.509Z [INFO]  client.plugin: shutting down plugin manager: plugin-type=driver
    2022-05-16T11:42:51.554Z [INFO]  client.plugin: plugin manager finished: plugin-type=driver
    2022-05-16T11:42:51.554Z [INFO]  client.plugin: shutting down plugin manager: plugin-type=csi
    2022-05-16T11:42:51.554Z [INFO]  client.plugin: plugin manager finished: plugin-type=csi
    2022-05-16T11:42:51.636Z [INFO]  agent: shutdown complete
nomad.service: Main process exited, code=exited, status=1/FAILURE
nomad.service: Failed with result 'exit-code'.
Stopped Nomad.
nomad.service: Found left-over process 15733 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15743 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15755 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15766 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15788 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15907 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16150 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16274 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16420 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16437 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16746 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16892 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 18358 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 18424 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19500 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19509 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19544 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19555 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19566 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19576 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19586 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19592 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19963 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19991 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20040 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20157 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20422 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20617 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21007 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21096 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21469 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21673 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 22190 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 24329 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 25803 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 25893 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started Nomad.
==> Loaded configuration from /etc/nomad.d/nomadclient.hcl, /etc/nomad.d/plugins.hcl
==> Starting Nomad agent...
2022-05-16T11:42:53.368Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.372Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.375Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.383Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.385Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.393Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.398Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.402Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.409Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.411Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.433Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.440Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.442Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.448Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.456Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.476Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.481Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.489Z [TRACE] plugin.stdio: waiting for stdio data
==> Nomad agent configuration:
       Advertise Addrs: HTTP: 10.177.83.139:4646
            Bind Addrs: HTTP: [0.0.0.0:4646]
                Client: true
             Log Level: INFO
                Region: global (DC: dc1)
                Server: false
               Version: 1.3.0
==> Nomad agent started! Log data will stream in below:
    2022-05-16T11:42:51.717Z [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/var/lib/nomad/plugins
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  client: using state directory: state_dir=/var/lib/nomad/client
    2022-05-16T11:42:51.720Z [INFO]  client: using alloc directory: alloc_dir=/var/lib/nomad/alloc
    2022-05-16T11:42:51.720Z [INFO]  client: using dynamic ports: min=20000 max=32000 reserved=""
    2022-05-16T11:42:51.722Z [INFO]  client.cpuset.v1: initialized cpuset cgroup manager: parent=/nomad cpuset=0-15
    2022-05-16T11:42:51.759Z [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
    2022-05-16T11:42:51.764Z [INFO]  client.fingerprint_mgr.consul: consul agent is available
    2022-05-16T11:42:51.803Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=ens3
    2022-05-16T11:42:51.805Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=lo
    2022-05-16T11:42:51.809Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=ens3
    2022-05-16T11:42:51.816Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=docker0
    2022-05-16T11:42:51.870Z [INFO]  client.fingerprint_mgr.vault: Vault is available
    2022-05-16T11:42:52.932Z [WARN]  client.fingerprint_mgr.env_aws: failed to find the cpu specification for this instance type
    2022-05-16T11:42:53.324Z [INFO]  client.plugin: starting plugin manager: plugin-type=csi
    2022-05-16T11:42:53.324Z [INFO]  client.plugin: starting plugin manager: plugin-type=driver
    2022-05-16T11:42:53.324Z [INFO]  client.plugin: starting plugin manager: plugin-type=device
    2022-05-16T11:42:53.331Z [INFO]  client.consul: discovered following servers: servers=[10.177.83.242:4647, 10.177.83.206:4647, 10.177.83.251:4647]
    2022-05-16T11:42:53.386Z [INFO]  client: node registration complete
    2022-05-16T11:42:53.489Z [INFO]  client: started client: node_id=12aa7338-c26e-7b38-f8e3-e05ce43b938a
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=351c27f9-1176-32f0-5984-a06c78083cd6
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=ed76561f-4a4d-3737-198a-2b05a8b7bd14
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=f7e22142-0f79-22ad-f470-9938ee95f2be
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=a6d27ae4-d78c-0eb6-a7ad-4ffb0d4000b3
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=cdbbbca0-4f38-aab9-cba7-aa04fe387deb
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=59077433-a255-cee6-e86f-8cc0ca64fff5
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=55a22db0-043e-1622-6900-efd95a6ebc34
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=b11dca3a-6003-d374-903c-aa1a679bb55b
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=5d808708-3b3f-7d75-8f84-2878bfe9866b
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=5dafa7ce-03b3-2c48-1b29-7dc08074e94b
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=7368b43d-5ab5-fcf7-9877-5b81a37492c6
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=a83c3fe7-31ae-3726-6267-db85c2e70a43
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=7216f331-038e-6f5c-8286-1413deeba57d
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=b77c8b9a-49e6-c611-ea8a-328dafef050a
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=45bdd92b-23f5-3c09-cd1f-f8f6926b1351
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=7ed89a3e-5dae-25af-3519-d370bcbfaa41
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=2d07c54d-cb0b-8dc7-ad41-e8c9cb067e34
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=9618e1b8-6ac2-0261-e223-54b906dac72b
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=10455e8f-a5dc-a693-cea4-ba2ace05e15e
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=c49754aa-d7ed-4f0b-6b8e-b988ccba087a
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=5d6a6be3-21cb-1857-4f3d-49bb9b19e717
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=8e6b028c-3d02-f644-ec54-c255b98fca4b
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=0e01cb08-eeb2-fc0e-bf39-adeed5555d5d
    2022-05-16T11:42:53.508Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.508Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.508Z [ERROR] client.alloc_runner: prerun failed: alloc_id=e753aac0-42ab-2b33-504d-b1734e79aad8 error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume elastic_test_data_az-1[0]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.alloc_runner: prerun failed: alloc_id=94ce152e-a06d-530d-6bb7-8c89b1d5b4df error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume csitest[1]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.alloc_runner: prerun failed: alloc_id=0dcf7f65-d665-a574-fdd1-54462182cba2 error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume csitest[0]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"
    2022-05-16T11:42:53.549Z [INFO]  agent: (runner) creating new runner (dry: false, once: false)
    2022-05-16T11:42:53.550Z [INFO]  agent: (runner) creating watcher
    2022-05-16T11:42:53.550Z [INFO]  agent: (runner) starting
    2022-05-16T11:42:53.563Z [INFO]  client.gc: marking allocation for GC: alloc_id=94ce152e-a06d-530d-6bb7-8c89b1d5b4df
    2022-05-16T11:42:53.568Z [INFO]  client.gc: marking allocation for GC: alloc_id=0dcf7f65-d665-a574-fdd1-54462182cba2
    2022-05-16T11:42:53.579Z [INFO]  client.gc: marking allocation for GC: alloc_id=e753aac0-42ab-2b33-504d-b1734e79aad8
    2022-05-16T11:42:53.588Z [INFO]  agent: (runner) creating new runner (dry: false, once: false)
```

**Comment by tgross** [comment]
Hi @rbastiaans-tc! The log lines that jump out at me here are:

>  2022-05-16T11:42:53.508Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
> 2022-05-16T11:42:53.508Z [ERROR] client.alloc_runner: prerun failed: alloc_id=e753aac0-42ab-2b33-504d-b1734e79aad8 error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume elastic_test_data_az-1[0]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"

What _should_ be happening here is:
* The client tries to restore its handle to the running allocation, and re-runs the `csi_hook.Prerun`.
* That send a "claim" RPC to the server
* The server sees that this is not a new claim (ref [`csi_endpoint.go#L454-L455`](https://github.com/hashicorp/nomad/blob/v1.3.0/nomad/csi_endpoint.go#L454-L455))
* The server skips the controller publish step (ref [`csi_endpoint.go#L482-L489`](https://github.com/hashicorp/nomad/blob/v1.3.0/nomad/csi_endpoint.go#L482-L489))

But it looks like from the client logs that we're sending the controller RPC anyways and that the `isNewClaim` calculation is simply incorrect for this case (the fix isn't yet obvious to be though, as we need to account for retried claim RPCs when the controller RPC fails intermittently). 

That being said, even if we are sending the controller RPC unexpectedly, I would not have expected the lookup for the node ID (ref [`csi_endpoint.go#L546-L551`](https://github.com/hashicorp/nomad/blob/v1.3.0/nomad/csi_endpoint.go#L546-L551)) to have failed unless the node plugin failed to fingerprint. That suggests there's either a race in plugin fingerprinting on restart or something is broken in persisting the plugin state.

Is there any chance the node plugin running on this host was previously running on a pre-1.3.0 client? That might help me narrow down what we're seeing here.

**Comment by tgross** [comment]
I've had a chance to take another look at this and the problem is pretty straightforwardly the `isNewClaim`; that bit of code is incorrectly assuming that if we're not getting a GC claim and the state is "taken", that it's new. That's causing the extra controller publish RPCs to be sent. The client has restarted, not become `lost`, so the server doesn't know that the plugins haven't been re-fingerprinted, and if it happens to pick a controller plugin on that node it'll fail to restore.

Ideally we should instead be getting the volume out of the state store and checking whether any of the claim fields have changed, except that we don't know whether the controller publish has succeeded without additional state. If we _only_ check if the claim is really new, we'd be unable to retry controller RPCs that fail after we've written the initial claim. So I think the thing to do here is to add a piece of state tracking this during the claim RPC. (We'll end up making 2 writes to raft instead of 1.)

**Comment by ygersie** [comment]
Hey @tgross we also ran into this issue and apart from triggering the failed allocations, Nomad also seems to lose track of the running containers meaning those containers will never be cleaned up.

**Comment by tgross** [comment]
@ygersie you have an open ticket with the Support team on that, which we're following up on independently. Let's keep this issue specific to the matter at hand.

**Comment by VictorEmmanuelPadel** [comment]
Hi @tgross, we are experiencing the same issue on our side.

When restarting the Nomad client, our allocations with CSI volumes can fail and are rescheduled. Rescheduled allocations don't work either and stay in a pending state because the volumes they were previously using aren't properly released.

We also get the following error: `failed to setup alloc: pre-run hook "csi_hook" failed: plugin nfs-csi for type csi-node not found` from the rescheduled allocations.

Additionally, while our allocations are failing from a Nomad pov, docker containers are still running.

Here are the conditions in which we reproduced the issue:
- Reproduced on both Nomad 1.3.2 and 1.3.7
- Heartbeat_grace threshold isn't reached so allocations don't become lost
- We are using the nfs-csi-plugin

**Comment by blmhemu** [comment]
Hey ! Can you try to tweak health_timeout to a longer period. That seems to have helped me some.

**Comment by tgross** [comment]
> Hey ! Can you try to tweak health_timeout to a longer period. That seems to have helped me some.

That's interesting and may point to the issue at hand: the fingerprinting can take a while to run (and this seems to be plugin-specific) and maybe our health_timeout is just too aggressive here.

**Comment by VictorEmmanuelPadel** [comment]
On our side we are using the default (30sec) value for the health_timeout stanza. We didn't try your solution @blmhemu because the documentation for that stanza talks about unhealthy CSI plugin which I don't think is the case here.

But if you both think we should give it a try any, let me know and we'll test it! :)

**Comment by blmhemu** [comment]
> > Hey ! Can you try to tweak health_timeout to a longer period. That seems to have helped me some.
> 
> That's interesting and may point to the issue at hand: the fingerprinting can take a while to run (and this seems to be plugin-specific) and maybe our health_timeout is just too aggressive here.

I observed this with nfs-csi https://gitlab.com/rocketduck/csi-plugin-nfs/-/issues/10

**Comment by ygersie** [comment]
@tgross I'm still running into a bug which I think is related to this issue as well. When I restart a Nomad client with CSI plugins (in this case just node plugins) the following happens:
```
    2023-02-16T12:26:53.196Z [INFO]  client: using state directory: state_dir=/data/nomad/client
    2023-02-16T12:26:53.196Z [INFO]  client: using alloc directory: alloc_dir=/data/nomad/alloc
    2023-02-16T12:26:53.196Z [INFO]  client: using dynamic ports: min=20000 max=32000 reserved=""
    2023-02-16T12:26:53.215Z [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
    2023-02-16T12:26:53.252Z [INFO]  client.fingerprint_mgr.consul: consul agent is available
    2023-02-16T12:26:53.301Z [INFO]  client.fingerprint_mgr.vault: Vault is available
    2023-02-16T12:27:03.304Z [INFO]  client.plugin: starting plugin manager: plugin-type=csi
    2023-02-16T12:27:03.304Z [INFO]  client.plugin: starting plugin manager: plugin-type=driver
    2023-02-16T12:27:03.304Z [INFO]  client.plugin: starting plugin manager: plugin-type=device
    2023-02-16T12:27:03.360Z [INFO]  client: started client: node_id=9ff3d071-f0c7-7caa-37e5-3060c81e2088
    2023-02-16T12:27:03.372Z [INFO]  client: node registration complete
    2023-02-16T12:27:03.375Z [ERROR] client.alloc_runner: prerun failed: alloc_id=0e8adeba-1dca-ed89-5d2a-7f06f29f55fc error="pre-run hook \"csi_hook\" failed: plugin ceph-rbd-csi for type csi-node not found"
    2023-02-16T12:27:03.376Z [ERROR] client.alloc_runner: prerun failed: alloc_id=8cf71002-2ff9-903b-58c0-bbd8253b8ec5 error="pre-run hook \"csi_hook\" failed: plugin ceph-rbd-csi for type csi-node not found"
    2023-02-16T12:27:03.376Z [ERROR] client.alloc_runner: prerun failed: alloc_id=00466ce2-1e93-675d-387b-078886fe75ae error="pre-run hook \"csi_hook\" failed: plugin ceph-rbd-csi for type csi-node not found"
```
So Nomad starts up, then reports that it's missing plugins. A few seconds after it stops the alloc that relies on a csi volume (id: `0e8adeba-1dca-ed89-5d2a-7f06f29f55fc`).

The log states:
```
    2023-02-16T12:27:07.377Z [INFO]  client.gc: marking allocation for GC: alloc_id=8cf71002-2ff9-903b-58c0-bbd8253b8ec5
    2023-02-16T12:27:07.673Z [WARN]  client.ceph-rbd-csi: finished client unary call: grpc.code=Internal duration=294.33976ms grpc.service=csi.v1.Node grpc.method=NodeUnstageVolume
    2023-02-16T12:27:07.962Z [WARN]  client.ceph-rbd-csi: finished client unary call: grpc.code=Internal duration=288.780727ms grpc.service=csi.v1.Node grpc.method=NodeUnstageVolume
    2023-02-16T12:27:09.378Z [INFO]  client.alloc_runner: waiting for task to exit: alloc_id=0e8adeba-1dca-ed89-5d2a-7f06f29f55fc task=redis
    2023-02-16T12:27:09.378Z [INFO]  client.gc: marking allocation for GC: alloc_id=0e8adeba-1dca-ed89-5d2a-7f06f29f55fc
```
"Waiting for task to exit", but it never did as I end up with a zombie container running that never exited and still has a busy volume claim. Nomad tries to schedule again but fails to claim the volume with the well known error: `volume max claims reached`. Even if it can schedule and it lands on the same box, because I now have a zombie container running I run into port conflicts. This is not an intermittent issue, every restart of nomad agent leads to new zombie containers of allocs that had a volume claim.

**Comment by tgross** [comment]
@ygersie do the plugins ever come up at all? If this is a race condition between plugin fingerprinting and the other allocations, that's one thing. Whereas if the plugins get completely lost after restart that's another.

**Comment by ygersie** [comment]
@tgross thanks for the quick response. Yeah, the plugins do come up after. There seems to be a couple of things at play here which I can reproduce every time I restart a client that runs allocations with CSI volumes. I just did it again on a different box with AWS CSI plugins (the previous was using Ceph). Summary:
* Nomad client starts up and fails to recover the running allocs as there's a race with the plugins. It seems that it runs `client.alloc_runner: prerun` for these on client startup which is where things go wrong since the plugins are not up yet.
* The client then marks the allocations as failed since it could not be "started" / reattached. This of course is not something that we want happening upon restarts of the Nomad agent.
* Nomad client then marks the alloc as failed and it should exit the task:
```
2023-02-17T08:56:55.952Z [INFO]  client.alloc_runner: waiting for task to exit: alloc_id=a90e6c74-035b-6073-70ba-d4853537f60e task=alertmanager
```
It also marks the alloc ready for GC:
```
2023-02-17T08:56:55.952Z [INFO]  client.gc: marking allocation for GC: alloc_id=a90e6c74-035b-6073-70ba-d4853537f60e
```
At this point we lose track of who owned the VolumeClaim. Looking at the volume status there's no allocation reference anymore. The container however is still running, it never exited which means it never even received a term signal even though the alloc is marked as failed.
* In this test with AWS CSI plugins the next scheduled allocation to replace `a90e6c74-035b-6073-70ba-d4853537f60e` is `201d2d8c-8fff-9d34-7842-7fdf0bd3c285` which starts out with failures regarding max claims reached:
```
2023-02-17T08:57:53.081Z [DEBUG] client.alloc_runner.runner_hook.csi_hook: volume could not be claimed because it is in use: alloc_id=201d2d8c-8fff-9d34-7842-7fdf0bd3c285 retry_in=32s
```
* At some point the Volume from the initial alloc (`a90e6c74-035b-6073-70ba-d4853537f60e`) is unmounted and released:
```
I0217 08:58:04.491417       1 node.go:426] NodeUnpublishVolume: called with args {VolumeId:vol-0d770beb16ae3d197 TargetPath:/local/csi/per-alloc/a90e6c74-035b-6073-70ba-d4853537f60e/alertmanager[1]/rw-file-system-single-node-writer XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0217 08:58:04.491472       1 node.go:444] NodeUnpublishVolume: unmounting /local/csi/per-alloc/a90e6c74-035b-6073-70ba-d4853537f60e/alertmanager[1]/rw-file-system-single-node-writer
I0217 08:58:04.491483       1 mount_linux.go:293] Unmounting /local/csi/per-alloc/a90e6c74-035b-6073-70ba-d4853537f60e/alertmanager[1]/rw-file-system-single-node-writer
I0217 08:58:04.492805       1 node.go:440] NodeUnPublishVolume: volume="vol-0d770beb16ae3d197" operation finished
I0217 08:58:04.492816       1 inflight.go:74] Node Service: volume="vol-0d770beb16ae3d197" operation finished
I0217 08:58:04.493141       1 node.go:254] NodeUnstageVolume: called with args {VolumeId:vol-0d770beb16ae3d197 StagingTargetPath:/local/csi/staging/alertmanager[1]/rw-file-system-single-node-writer XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0217 08:58:04.493447       1 node.go:294] NodeUnstageVolume: unmounting /local/csi/staging/alertmanager[1]/rw-file-system-single-node-writer
I0217 08:58:04.493484       1 mount_linux.go:293] Unmounting /local/csi/staging/alertmanager[1]/rw-file-system-single-node-writer
I0217 08:58:04.494566       1 node.go:269] NodeUnStageVolume: volume="vol-0d770beb16ae3d197" operation finished
I0217 08:58:04.494578       1 inflight.go:74] Node Service: volume="vol-0d770beb16ae3d197" operation finished
```
I'm not sure why the unmount worked with the EBS plugin since the container is still running with this volume but it does succeed. In my comment above this one with the Ceph volume we keep seeing:
```
2023-02-16T12:27:07.962Z [WARN]  client.ceph-rbd-csi: finished client unary call: grpc.code=Internal duration=288.780727ms grpc.service=csi.v1.Node grpc.method=NodeUnstageVolume
```
over and over, because the plugin fails to umount the volume as the resource is busy. The issue I think is exactly the same though, the container is still running, it never received a term signal while the alloc is marked as failed and GC-ed.

In this scenario, because the volume is released and it could be rescheduled I now end up with a port binding issue as we have a zombie container running:
```
2023-02-17T08:58:32.097Z [DEBUG] client.driver_mgr.docker: failed to start container: driver=docker container_id=9c0be2438db79f34fb66a2cb1c9700f36aa6306193d66ba06aa5d176caa2ed2d attempt=1 error="API error (500): driver failed programming external connectivity on endpoint alertmanager-201d2d8c-8fff-9d34-7842-7fdf0bd3c285 (aea0b65f879cf5b2c4d40d60d0e8f773024ca56d55f8c4fd7c9182ac632e61f1): Bind for 10.97.10.200:9094 failed: port is already allocated"
```

In case we run an orchestrated restart to have Nomad pickup config changes you can probably imagine the gigantic mess we end up with.

**Comment by rismoney** [comment]
Is there a way we can get this bug prioritized for fixing?  I feel like it is very problematic to upgrade nomad nodes, knowing that allocs depending on CSI are going to be borked upon service restart.

**Comment by gulducat** [comment]
Heya folks!  This should be fixed by #16809 which will ship in the next release, including backports for 1.5.x, 1.4.x, and 1.3.x.

If anyone would like to take it for a test drive to confirm resolution before the next release goes out, please let us know how it goes!

**Comment by ygersie** [comment]
@gulducat I just tested this on AWS with a build from master but still have the same issue with the EBS driver, see logs attached. It looks like the client on startup performs a call to the controller which assumes the client's plugin is fingerprinted, which it isn't at that point in time. The allocation then fails:
```
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created     Modified
67f820cb  13a1edc2  ygersie     1        run      running   1m7s ago    53s ago
4c56c7cc  13a1edc2  ygersie     1        stop     failed    11m55s ago  1m7s ago

Recent Events:
Time                       Type           Description
2023-04-14T14:02:40+02:00  Setup Failure  failed to setup alloc: pre-run hook "csi_hook" failed: claim volumes: could not claim volume ygersie-test[0]: rpc error: rpc error: controller publish: failed to find storage provider info for client "13a1edc2-c5e0-d932-e5a8-7da42f645769", node plugin "aws-ebs" is not running or has not fingerprinted on this client
2023-04-14T13:55:56+02:00  Started        Task started by client
2023-04-14T13:55:54+02:00  Driver         Downloading image
2023-04-14T13:55:54+02:00  Task Setup     Building Task Directory
2023-04-14T13:55:52+02:00  Received       Task received by client
```

However, the docker container is not stopped/removed:
```
root@ip-10-134-9-39:~# docker ps | grep 4c56c7cc
15dc5c3a83a5   alpine                                                          "tail -f /dev/null"      12 minutes ago       Up 12 minutes                          ygersie-4c56c7cc-1337-8298-57a6-fbc54263761c
```

```
==> Nomad agent configuration:

       Advertise Addrs: HTTP: 10.134.9.39:4646
            Bind Addrs: HTTP: [0.0.0.0:4646]
                Client: true
             Log Level: DEBUG
                Region: eu-west-2 (DC: eu-west-2b)
                Server: false
               Version: 1.5.4-dev

==> Nomad agent started! Log data will stream in below:

    2023-04-14T12:02:39.607Z [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/data/nomad/plugins
    2023-04-14T12:02:39.612Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/data/nomad/plugins
    2023-04-14T12:02:39.612Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/data/nomad/plugins
    2023-04-14T12:02:39.613Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
    2023-04-14T12:02:39.613Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    2023-04-14T12:02:39.613Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
    2023-04-14T12:02:39.613Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
    2023-04-14T12:02:39.613Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
    2023-04-14T12:02:39.644Z [INFO]  client: using state directory: state_dir=/data/nomad/client
    2023-04-14T12:02:39.644Z [INFO]  client: using alloc directory: alloc_dir=/data/nomad/alloc
    2023-04-14T12:02:39.644Z [INFO]  client: using dynamic ports: min=20000 max=32000 reserved=""
    2023-04-14T12:02:39.644Z [INFO]  client.cpuset.v1: initialized cpuset cgroup manager: parent=/nomad cpuset=0-1
    2023-04-14T12:02:39.650Z [DEBUG] client.fingerprint_mgr: built-in fingerprints: fingerprinters=["arch", "bridge", "cgroup", "cni", "consul", "cpu", "host", "landlock", "memory", "network", "nomad", "plugins_cni", "signal", "storage", "vault", "env_azure", "env_digitalocean", "env_aws", "env_gce"]
    2023-04-14T12:02:39.650Z [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
    2023-04-14T12:02:39.651Z [DEBUG] client.fingerprint_mgr: CNI config dir is not set or does not exist, skipping: cni_config_dir=/opt/cni/config
    2023-04-14T12:02:39.653Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=cgroup initial_period=15s
    2023-04-14T12:02:39.713Z [INFO]  client.fingerprint_mgr.consul: consul agent is available
    2023-04-14T12:02:39.714Z [DEBUG] client.fingerprint_mgr.cpu: detected CPU model: name="Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz"
    2023-04-14T12:02:39.714Z [DEBUG] client.fingerprint_mgr.cpu: detected CPU frequency: mhz=2499
    2023-04-14T12:02:39.714Z [DEBUG] client.fingerprint_mgr.cpu: detected CPU core count: EXTRA_VALUE_AT_END=2
    2023-04-14T12:02:39.714Z [DEBUG] client.fingerprint_mgr.cpu: client configuration reserves these cores for node: cores=[]
    2023-04-14T12:02:39.714Z [DEBUG] client.fingerprint_mgr.cpu: set of reservable cores available for tasks: cores=[0, 1]
    2023-04-14T12:02:39.716Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=consul initial_period=15s
    2023-04-14T12:02:39.718Z [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/eth0/speed device=eth0
    2023-04-14T12:02:39.718Z [DEBUG] client.fingerprint_mgr.network: link speed could not be detected and no speed specified by user, falling back to default speed: interface=eth0 mbits=1000
    2023-04-14T12:02:39.718Z [DEBUG] client.fingerprint_mgr.network: detected interface IP: interface=eth0 IP=10.134.9.39
    2023-04-14T12:02:39.719Z [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/lo/speed device=lo
    2023-04-14T12:02:39.719Z [DEBUG] client.fingerprint_mgr.network: link speed could not be detected, falling back to default speed: interface=lo mbits=1000
    2023-04-14T12:02:39.723Z [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/eth0/speed device=eth0
    2023-04-14T12:02:39.723Z [DEBUG] client.fingerprint_mgr.network: link speed could not be detected, falling back to default speed: interface=eth0 mbits=1000
    2023-04-14T12:02:39.728Z [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/discovery/speed device=discovery
    2023-04-14T12:02:39.728Z [DEBUG] client.fingerprint_mgr.network: link speed could not be detected, falling back to default speed: interface=discovery mbits=1000
    2023-04-14T12:02:40.272Z [INFO]  client.fingerprint_mgr.vault: Vault is available
    2023-04-14T12:02:40.273Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=vault initial_period=1m36.332290445s
    2023-04-14T12:02:40.273Z [DEBUG] client.fingerprint_mgr.env_gce: could not read value for attribute: attribute=machine-type resp_code=404
    2023-04-14T12:02:40.274Z [DEBUG] client.fingerprint_mgr.env_azure: could not read value for attribute: attribute=compute/azEnvironment resp_code=404
    2023-04-14T12:02:40.275Z [DEBUG] client.fingerprint_mgr.env_digitalocean: could not read value for attribute: attribute=region resp_code=404
    2023-04-14T12:02:40.277Z [DEBUG] client.fingerprint_mgr.env_aws: read an empty value: attribute=public-hostname
    2023-04-14T12:02:40.280Z [DEBUG] client.fingerprint_mgr.env_aws: read an empty value: attribute=public-ipv4
    2023-04-14T12:02:40.283Z [DEBUG] client.fingerprint_mgr.env_aws: read an empty value: attribute=network/interfaces/macs/0a:43:fc:65:46:a0/ipv6s
    2023-04-14T12:02:40.283Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu: cores=2 ghz=2.5
    2023-04-14T12:02:40.283Z [DEBUG] client.fingerprint_mgr.env_aws: setting ec2 cpu: ticks=5000
    2023-04-14T12:02:40.283Z [DEBUG] client.fingerprint_mgr: detected fingerprints: node_attrs=["arch", "bridge", "cgroup", "consul", "cpu", "host", "network", "nomad", "plugins_cni", "signal", "storage", "vault", "env_aws"]
    2023-04-14T12:02:40.283Z [INFO]  client.plugin: starting plugin manager: plugin-type=csi
    2023-04-14T12:02:40.283Z [INFO]  client.plugin: starting plugin manager: plugin-type=driver
    2023-04-14T12:02:40.283Z [INFO]  client.plugin: starting plugin manager: plugin-type=device
    2023-04-14T12:02:40.283Z [DEBUG] client.device_mgr: exiting since there are no device plugins
    2023-04-14T12:02:40.284Z [DEBUG] client.plugin: waiting on plugin manager initial fingerprint: plugin-type=driver
    2023-04-14T12:02:40.285Z [DEBUG] client.plugin: waiting on plugin manager initial fingerprint: plugin-type=device
    2023-04-14T12:02:40.285Z [DEBUG] client.plugin: finished plugin manager initial fingerprint: plugin-type=device
    2023-04-14T12:02:40.285Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=raw_exec health=undetected description=disabled
    2023-04-14T12:02:40.285Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=exec health=healthy description=Healthy
    2023-04-14T12:02:40.285Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=qemu health=undetected description=""
    2023-04-14T12:02:40.285Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=java health=undetected description=""
    2023-04-14T12:02:40.315Z [DEBUG] client.driver_mgr.docker: bridge_ip could not be discovered: driver=docker
    2023-04-14T12:02:40.324Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=docker health=healthy description=Healthy
    2023-04-14T12:02:40.324Z [DEBUG] client.driver_mgr: detected drivers: drivers="map[healthy:[exec docker] undetected:[raw_exec qemu java]]"
    2023-04-14T12:02:40.324Z [DEBUG] client.plugin: finished plugin manager initial fingerprint: plugin-type=driver
    2023-04-14T12:02:40.325Z [DEBUG] client.server_mgr: new server list: new_servers=[10.134.0.101:4647] old_servers=[]
    2023-04-14T12:02:40.328Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=004c3051-41df-c934-8fb3-b8c840b3e67a task=cadvisor type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.332Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=17149713-bc4b-cf5f-0698-226e3ce19710 task=ygersie type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.333Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=4b9d40e8-afa7-8d85-0924-146f989975be task=fluent-bit type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.336Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=4c56c7cc-1337-8298-57a6-fbc54263761c task=ygersie type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.339Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=a5d81c08-a12e-b76f-3ec9-2d6de12fbd23 task=csi-ebs-nodes type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.344Z [DEBUG] client.server_mgr: new server list: new_servers=[10.134.0.101:4647, 10.134.0.103:4647, 10.134.0.152:4647] old_servers=[10.134.0.101:4647]
    2023-04-14T12:02:40.344Z [INFO]  client: node registration complete
    2023-04-14T12:02:40.344Z [DEBUG] client: evaluations triggered by node registration: num_evals=5
    2023-04-14T12:02:40.344Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=b03a725d-118d-4863-3e71-5d68dd42cb60 task=ygersie type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.348Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=d46f6869-7972-09a5-4d77-9d14c446e8d7 task=ygersie type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.351Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=e4337190-1921-f9c0-304f-88e500743c9f task=csi-efs-node type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.351Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=e4337190-1921-f9c0-304f-88e500743c9f task=csi-controller-health type=Received msg="Task received by client" failed=false
    2023-04-14T12:02:40.355Z [INFO]  client: started client: node_id=13a1edc2-c5e0-d932-e5a8-7da42f645769
    2023-04-14T12:02:40.355Z [WARN]  agent: not registering Nomad HTTPS Health Check because verify_https_client enabled
    2023-04-14T12:02:40.356Z [DEBUG] http: UI is disabled in this build
    2023-04-14T12:02:40.357Z [DEBUG] http: UI is disabled in this build
    2023-04-14T12:02:40.358Z [DEBUG] client.alloc_runner.task_runner: lifecycle start condition has been met, proceeding: alloc_id=4b9d40e8-afa7-8d85-0924-146f989975be task=fluent-bit
    2023-04-14T12:02:40.358Z [INFO]  client.gc: marking allocation for GC: alloc_id=b03a725d-118d-4863-3e71-5d68dd42cb60
    2023-04-14T12:02:40.361Z [INFO]  client.gc: marking allocation for GC: alloc_id=17149713-bc4b-cf5f-0698-226e3ce19710
    2023-04-14T12:02:40.363Z [DEBUG] client.driver_mgr.docker: image reference count incremented: driver=docker image_name=gcr.io/google_containers/pause-amd64:3.1 image_id=sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e references=1
    2023-04-14T12:02:40.364Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: rpc error: controller publish: failed to find storage provider info for client \"13a1edc2-c5e0-d932-e5a8-7da42f645769\", node plugin \"aws-ebs\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.134.0.101:4647
    2023-04-14T12:02:40.364Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: rpc error: controller publish: failed to find storage provider info for client \"13a1edc2-c5e0-d932-e5a8-7da42f645769\", node plugin \"aws-ebs\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.134.0.101:4647
    2023-04-14T12:02:40.364Z [ERROR] client.alloc_runner: prerun failed: alloc_id=4c56c7cc-1337-8298-57a6-fbc54263761c error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume ygersie-test[0]: rpc error: rpc error: controller publish: failed to find storage provider info for client \"13a1edc2-c5e0-d932-e5a8-7da42f645769\", node plugin \"aws-ebs\" is not running or has not fingerprinted on this client"
    2023-04-14T12:02:40.368Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=4c56c7cc-1337-8298-57a6-fbc54263761c task=ygersie type="Setup Failure" msg="failed to setup alloc: pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume ygersie-test[0]: rpc error: rpc error: controller publish: failed to find storage provider info for client \"13a1edc2-c5e0-d932-e5a8-7da42f645769\", node plugin \"aws-ebs\" is not running or has not fingerprinted on this client" failed=true
```

**Comment by ygersie** [comment]
@gulducat shouldn't the condition [here](https://github.com/hashicorp/nomad/blob/v1.5.3/nomad/csi_endpoint.go#L436-L437) instead of
```
isNewClaim := args.State == structs.CSIVolumeClaimStateTaken
```
not be
```
isNewClaim := args.State != structs.CSIVolumeClaimStateTaken
```
It's supposed to determine if it's a new claim, now it's true if the state is ClaimStateTaken?

**Comment by tgross** [comment]
@ygersie if that were the case, controllers would never work in the first place, right? Presumably you're still talking about agent restart scenarios here? We've still got https://github.com/hashicorp/nomad/issues/15415 open to discuss the various controller plugin issues you're seeing. Let's keep the conversation over there.

**Comment by ygersie** [comment]
@tgross just to make sure, the changes that have been done in https://github.com/hashicorp/nomad/pull/16809 only affect the clients right? That’s what I tested and the output above comes from an upgraded client built from master. But this issue, that the original poster created, is the exact same issue I’m still running into now, which happens on the server. The error was and still is:
```
rpc error: rpc error: controller publish: failed to find storage provider info for client
```
So I think this issue should be reopened.

**Comment by tgross** [comment]
Sure, opening. We'll address this next time we have a window to look into CSI.

**Comment by tgross** [comment]
>  But this issue, that the original poster created, is the exact same issue I’m still running into now, which happens on the server. The error was and still is:

@ygersie _during client restart_, or not?

**Comment by ygersie** [comment]
@tgross yeah, during client restart.

**Comment by tgross** [comment]
And there's more than one controller running, so that the controller we're talking to isn't on the client that's getting restarted, right?

**Comment by ygersie** [comment]
There's only a single controller running (due to the race condition issue in device name assignments) but it's not running on this client. This client was added without any other allocations running on them just to test the restarts. The worst thing is that Nomad garbage collects the failed allocation but doesn't actually shutdown the docker container (checked the docker logs it never received the api call to stop it either), leaving a zombie container.

**Comment by tgross** [comment]
Ok, then I'm going to re-close this issue. As I noted in #15415 it's already documented that should be run HA and there's already a mechanism to handle retries across controllers that aren't available. If you run controllers HA and find that mechanism isn't working, open a new bug for that please. If you want to talk about changing the behavior that's a feature request and one you should probably escalate with your field rep.

**Comment by ygersie** [comment]
@tgross I'm not following? What I mentioned in https://github.com/hashicorp/nomad/issues/15415#issuecomment-1487369495 is that the ebs controller can not run concurrently since it has a race condition in assigning device names. When that happens Nomad fails the allocation permanently and never releases the claim (which it should) making things even worse since now you'll have to forcefully re-register the volume to get Nomad to release.

This issue is different since the error is coming from: https://github.com/hashicorp/nomad/blob/main/nomad/csi_endpoint.go#L532 and has nothing to do with the controller. It throws an error stating the client plugin isn't couldn't be found while trying to execute the controllerpublish which was triggered by the volumeClaim(). Exactly like you described here: https://github.com/hashicorp/nomad/issues/13028#issuecomment-1127692598

**Comment by ygersie** [comment]
Again, this is the same issue as described by the OP (@rbastiaans-tc) if you take a look at the exact error reported. This issue should be re-opened as what was addressed in https://github.com/hashicorp/nomad/pull/16809 doesn't solve the issue described here.

**Comment by tgross** [comment]
Re-opening. I'll come back to this when I next have an open cycle.

**Comment by tgross** [comment]
I'm picking this issue back up and I think I've got a promising line of investigation going. Starting from the log message:

> 2023-04-14T14:02:40+02:00  Setup Failure  failed to setup alloc: pre-run hook "csi_hook" failed: claim volumes: could not claim volume ygersie-test[0]: rpc error: rpc error: controller publish: failed to find storage provider info for client "13a1edc2-c5e0-d932-e5a8-7da42f645769", node plugin "aws-ebs" is not running or has not fingerprinted on this client

Note that it's showing "controller publish" but "node plugin... is not running". Which as @ygersie has pointed out is a message about the plugin running on the client (the "node plugin").

**Background:** Whenever we send a publish message to the controller, we need to tell it the _external_ identifier of the host we're intending to publish. This external ID is provider-specific, for example the EC2 instance ID `i-0af01c0123456789a`. The only place to get that external ID is from the node plugin where we want to place the volume, so when the node plugin starts up we send the external ID up to the server as part of the plugin's fingerprint. A mapping of Nomad clients to CSI plugin instances and their external IDs is persisted in the Nomad state store on the `CSIPlugin` object.

So when we perform any controller operation that needs the external ID, we should be using the following logic to find the external ID (ref [`csi_endpoint.go#L876`](https://github.com/hashicorp/nomad/blob/v1.5.6/nomad/csi_endpoint.go#L876)):
1. Use the external ID provided by request
2. Use the external ID previously associated with the volume claim
3. Failing that, lookup the node plugin in the state store

**Problem**: On close examination, there are actually several problems here:

* The controller publish workflow simply skips both the first two steps! (ref [`csi_endpoint.go#L525-L532`](https://github.com/hashicorp/nomad/blob/v1.5.6/nomad/csi_endpoint.go#L525-L532))
* The [`CSIVolume.Claim`](https://github.com/hashicorp/nomad/blob/v1.5.6/nomad/csi_endpoint.go#L409) RPC should be able to identify that there's no need to send a controller RPC for a restarted client, because we're already published to the node. (This is a little tricky because the whole thing is supposed to be idempotent and that's important for repair.)
* The [`csi_hook`](https://github.com/hashicorp/nomad/blob/v1.5.6/client/allocrunner/csi_hook.go) doesn't wait for the node plugin to exist before making the claim. In https://github.com/hashicorp/nomad/pull/16809 we added blocking the _node_ plugin operations until the node plugin was ready, but if the plugin isn't in the server's state store we want to be blocking the claim step as well.
* Relatedly, the `csi_hook` on the client doesn't send an external ID with the claim (which we could retrieve from the plugin manager on that client if the plugin was fingerprinted).
* When the client starts, it sends a fingerprint that does _not_ include any previously-running plugins. Restoring the client's allocations, which lets us run the plugin fingerprints, happens well after the initial client fingerprint. So right now there's no way to avoid "flapping" the plugin health during client restarts. (ref [`client.go#L465`](https://github.com/hashicorp/nomad/blob/v1.5.6/client/client.go#L465) vs [`client.go#L550`](https://github.com/hashicorp/nomad/blob/v1.5.6/client/client.go#L550))

I suspect that if we had only one or two of these problems the whole thing might work, but definitely with them all together the "holes in the swiss cheese" all line up and we get the unfortunate behavior described in this issue.

**Solution:** I'm working up a patch series to do the following:
* Update the `CSIVolume.Claim` RPC to avoid starting the controller publish workflow unnecessarily during restore.
* Update the controller publish workflow to check the incoming claim (or previous claim) for the external ID.
* Have the `csi_hook` block the claim RPC on the node plugin being fingerprinted so we can send the external ID with the claim.
* Have the CSI plugin fingerprints persisted to client state so that we don't "flap" the plugin availability during client restarts. Then when we hit the allocation restore, we can remove the plugins if the plugin allocations have failed in the meantime.

I'll be getting started on that tomorrow. I'd really like for this to land in 1.6.0 GA but the testing requirements to really ensure we've put this to bed may mean it slips to a fast-follow 1.6.1. I'll keep this issue updated with progress.

**Comment by tgross** [comment]
Ok, I've got a working branch in [`csi-agent-restart-13028`](https://github.com/hashicorp/nomad/compare/csi-agent-restart-13028) that partially implements the plan above. A complication I ran into is that the volume request in the jobspec doesn't include the plugin ID, because we don't want job submitters to care about this. So without querying the server we don't have the plugin ID so that we can check it's running. I've handled this hackily for the moment by having the client make a `CSIVolume.Get` to the server before it blocks on the plugins and this "works". But not only does this add an extra round trip, it means that restarting clients that are disconnected from the server will fail to restore allocations that need CSI volumes. That's a bug with the current design as well but no need to make it worse.

So the next step is to persist at least a partial fingerprint with plugin ID and the external node ID somewhere in client state so that we can restore it without talking to the server. That opens the door to avoiding having to send the CSI RPCs entirely during restore.

It's a long weekend here in the US so I'm going to pick this back up on Wednesday, but making good progress and hoping to start E2E testing of it fairly soon.

**Comment by tgross** [comment]
Hey folks, the working branch has been updated with the current approach, which is to:
* Persist a minimum subset of data about the volume and its plugin in the client state DB, and retrieve that data during the CSI hook's prerun to avoid re-claiming and remounting the volume unnecessarily.
* If there is no locally-stored data about the plugin, go to the server.
* Get the external node ID from the plugin and use it in the claim RPC so as to reduce the risk of a flapping node plugin fingerprint causing problems once the request gets to the server.

I've got some end-to-end testing of this to do tomorrow and then I'll polish that up for a PR.

**Comment by tgross** [comment]
Ok, I've got https://github.com/hashicorp/nomad/pull/17840 up. One major change from the above is that I determined the extra `CSIVolumes.Get` was unnecessary as it's racy if the node plugins are in a flapping state during the initial placement so it doesn't get us any additional reliability and adds one more thing that can go wrong. The local state check ends up being enough. I've marked that for review and we'll look to ship that with the upcoming 1.6.0-rc.1 (and the eventual 1.6.0 GA + backports).

**Comment by tgross** [comment]
Fixed in #17840 which will ship in Nomad 1.6.0 (with backports)
