### ISSUE TITLE
current nomad documentation (getting started/cluster) wrong

### ISSUE THREAD

**Issue by mbravorus** [hashicorp/nomad#2114]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.5.1

### Operating system and Environment details
macOS sierra with vagrant 1.9.1 with Vagrantfile from https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile

### Issue

when attempting to follow https://www.nomadproject.io/intro/getting-started/cluster.html (having performed all the previous steps successfully) server startup fails with 

```
vagrant@nomad:~$ sudo nomad agent -config server.hcl
==> Failed to parse HTTP advertise address: No valid advertise addresses, please set `advertise` manually
```

### Reproduction steps
see above

With some Googling I think I understand where the problem is coming from, however the current documentation doesn't seem to have any bind/advertise statements in provided server.hcl and thus actively misleads newcomers

**Comment by mbravorus** [comment]
Similarly, client configs do not work as specified because of 127.0.0.1 in server specification

**Comment by schmichael** [comment]
Both documentation and Vagrantfile fix is in #2122

Basically setting `advertise` to localhost could do Really Bad Things if done in a production cluster, so the 0.5 started disallowing it. Sadly I didn't notice that broke our tutorial. Sorry, and thanks for the bug report!

**Comment by matt-e** [comment]
Looks like this was broken again by https://github.com/hashicorp/nomad/commit/8ed23d4b2894da4657a8479a11d6c6070818ab30

**Comment by schmichael** [comment]
@matt-e The getting started vagrantfile should be fixed as of #2822 getting merged

**Comment by lmunro** [comment]
@schmichael i used the vagrant file from https://github.com/hashicorp/nomad/pull/2822/files and still getting the same error

**Comment by bundyfx** [comment]
running through the Nomad getting started right now, this is still broken.
