### ISSUE TITLE
Nil dereference after 1.7.5 update

### ISSUE THREAD

**Issue by morphine1900** [hashicorp/nomad#23659]
### Nomad version
Output from `nomad version`
1.7.5

### Operating system and Environment details
Linux amd64

### Issue
Nil dereference on running job after updating to 1.7.5

### Nomad Client logs (if appropriate)

```
nomad[11069]: \nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2a88140?, 0x4f5ea50?})\n\truntime/panic.go:914 +0x21f\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:258\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00190e320)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3185 +0xcc\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc00145b048, 0xc00148c600)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc000127810)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc00066c1c0)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:816 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc00191a880, 0xc001636a20, 0xc00145b790)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc001d1c3c0, {0xc00191a980, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc001d1c3c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb85\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc001d1c3c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc00145bd80, 0xc00145bd70)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc001d1c3c0, 0xc002200480)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc0012a76c0, 0xc001154420, 0xc002200480, {0xc001e6f7d0, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x353\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc0012a76c0, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x5a5\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: {"@level":"error","@message":"processing eval panicked scheduler - please report this as a bug!","@module":"worker.system_sched","@timestamp":"2024-07-20T00:08:01.615847Z","error":"runtime error: invalid memory address or nil pointer dereference","eval_id":"33a13e15-fa8c-c2b6-5437-272e0a5b9c0a","job_id":"m3hostfiles","namespace":"default","stack_trace":"goroutine 65 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2a88140?, 0x4f5ea50?})\n\truntime/panic.go:914 +0x21f\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:258\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00190e320)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3185 +0xcc\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc00145b048, 0xc00148c600)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc000127810)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc00066c1c0)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:816 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc00191a880, 0xc001636a20, 0xc00145b790)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc001d1c3c0, {0xc00191a980, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc001d1c3c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb85\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc001d1c3c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc00145bd80, 0xc00145bd70)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc001d1c3c0, 0xc002200480)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc0012a76c0, 0xc001154420, 0xc002200480, {0xc001e6f7d0, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x353\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc0012a76c0, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x5a5\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2024-07-20T00:08:01.616029Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2024-07-20T00:08:01.616029Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: \nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2a88140?, 0x4f5ea50?})\n\truntime/panic.go:914 +0x21f\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:258\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00190e320)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3185 +0xcc\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc00145b048, 0xc00148c600)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc00069e230)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc000efcfa0)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:816 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc002870d00, 0xc001636a20, 0xc00145b790)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc00178a0c0, {0xc002870e00, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc00178a0c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb85\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc00178a0c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc00145bd80, 0xc00145bd70)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc00178a0c0, 0xc001994000)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc0012a76c0, 0xc001226540, 0xc001994000, {0xc0036ab650, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x353\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc0012a76c0, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x5a5\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: {"@level":"error","@message":"processing eval panicked scheduler - please report this as a bug!","@module":"worker.system_sched","@timestamp":"2024-07-20T00:08:02.619052Z","error":"runtime error: invalid memory address or nil pointer dereference","eval_id":"33a13e15-fa8c-c2b6-5437-272e0a5b9c0a","job_id":"m3hostfiles","namespace":"default","stack_trace":"goroutine 65 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2a88140?, 0x4f5ea50?})\n\truntime/panic.go:914 +0x21f\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:258\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00190e320)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3185 +0xcc\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc00145b048, 0xc00148c600)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc00069e230)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc000efcfa0)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:816 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc002870d00, 0xc001636a20, 0xc00145b790)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc00178a0c0, {0xc002870e00, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc00178a0c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb85\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc00178a0c0)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc00145bd80, 0xc00145bd70)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc00178a0c0, 0xc001994000)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc0012a76c0, 0xc001226540, 0xc001994000, {0xc0036ab650, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x353\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc0012a76c0, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x5a5\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2024-07-20T00:08:02.619112Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
nomad[11069]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2024-07-20T00:08:02.619112Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"0b7cd3e0-f1d4-bab0-9843-e6eef610aa25"}
```

**Comment by jrasell** [comment]
Hi @morphine1900 and thanks for raising this.

Is it possible to provide some more information, so I could reproduce this? It would be very handy to have a redacted version of the job specification that was being processed at the time and an output of a Nomad client either by the [CLI](https://developer.hashicorp.com/nomad/docs/commands/node/status) or [API](https://developer.hashicorp.com/nomad/api-docs/nodes#read-node) that would have been eligible to run this work.

**Comment by tgross** [comment]
Hi @morphine1900 I took a look at your log entry and extracted the following stack trace:

<details><summary>stack trace</summary>

```
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()
	github.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58
panic({0x2a88140?, 0x4f5ea50?})
	runtime/panic.go:914 +0x21f
github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)
	github.com/hashicorp/nomad/client/lib/numalib/topology.go:258
github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00190e320)
	github.com/hashicorp/nomad/nomad/structs/structs.go:3185 +0xcc
github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc00145b048, 0xc00148c600)
	github.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36
github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc000127810)
	github.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d
github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc00066c1c0)
	github.com/hashicorp/nomad/scheduler/rank.go:816 +0x28
github.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc00191a880, 0xc001636a20, 0xc00145b790)
	github.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e
github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc001d1c3c0, {0xc00191a980, 0x3, 0xb?})
	github.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325
github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc001d1c3c0)
	github.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb85
github.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc001d1c3c0)
	github.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da
github.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc00145bd80, 0xc00145bd70)
	github.com/hashicorp/nomad/scheduler/util.go:96 +0x49
github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc001d1c3c0, 0xc002200480)
	github.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525
github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc0012a76c0, 0xc001154420, 0xc002200480, {0xc001e6f7d0, 0x24})
	github.com/hashicorp/nomad/nomad/worker.go:634 +0x353
github.com/hashicorp/nomad/nomad.(*Worker).run(0xc0012a76c0, 0x12a05f200)
	github.com/hashicorp/nomad/nomad/worker.go:463 +0x5a5
created by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1
	github.com/hashicorp/nomad/nomad/worker.go:162 +0x59
```

</details>

This looks an awful lot like it's rooted in the same bug I fixed here https://github.com/hashicorp/nomad/pull/23284, which shipped in Nomad 1.8.1, with backports to 1.7.10 Enterprise and 1.6.13 Enterprise. In addition to providing what @jrasell's asked for, you may want to try upgrading to Nomad 1.8.x to see if the problem's already been fixed for you.

**Comment by morphine1900** [comment]
it still happened on 1.8.3
`
nomad[11736]: \nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2b61cc0?, 0x52e7bc0?})\n\truntime/panic.go:770 +0x132\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:281\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc001bf17c0)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3220 +0xcc\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc00005d2b8, 0xc000323c80)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc001e20070)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:275 +0x745\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc0018e0500)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:821 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc000d90100, 0xc0016dd680, 0xc00005d8d0)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82c\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc001fda180, {0xc000d90200, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc001fda180)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb30\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc001fda180)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4c5\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc00005dda8, 0xc00005dd78)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:97 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc001fda180, 0xc002180180)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x505\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc000d760e0, 0xc00183aab0, 0xc002180180, {0xc001a1e7b0, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x33b\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc000d760e0, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x585\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n"`

**Comment by jrasell** [comment]
Hi @morphine1900, would you be able to provide some additional detail, as previously requested please?

> Is it possible to provide some more information, so I could reproduce this? It would be very handy to have a redacted version of the job specification that was being processed at the time and an output of a Nomad client either by the [CLI](https://developer.hashicorp.com/nomad/docs/commands/node/status) or [API](https://developer.hashicorp.com/nomad/api-docs/nodes#read-node) that would have been eligible to run this work.

> The title suggests you upgraded Nomad, could you also let me know what version you upgraded from please?

**Comment by morphine1900** [comment]
Now it's in 1.9.5:
`Jan 18 02:29:16 nomad[24428]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2025-01-18T02:29:16.188016Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
Jan 18 02:29:16 nomad[24428]: \nruntime/debug.Stack()\n\truntime/debug/stack.go:26 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2d99520?, 0x54eac00?})\n\truntime/panic.go:785 +0x132\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(0x0)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:290 +0x9f\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00176a5a0)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3287 +0x33\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc002387238, 0xc0020bca80)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:165 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc000679810)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:279 +0x7b2\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc001fd8a80)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:1013 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc003131980, 0xc00167c900, 0xc0023878d0)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x825\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc0039fae40, {0xc003131a80, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc0039fae40)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb30\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc0039fae40)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4c5\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc002387da8, 0xc002387d78)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:97 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc0039fae40, 0xc001adcc00)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x4d3\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc000f58d20, 0xc0013715f0, 0xc001adcc00, {0xc00604b980, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x352\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc000f58d20, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x585\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
Jan 18 02:29:16 nomad[24428]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2025-01-18T02:29:16.188016Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
Jan 18 02:29:17 nomad[24428]: \nruntime/debug.Stack()\n\truntime/debug/stack.go:26 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2d99520?, 0x54eac00?})\n\truntime/panic.go:785 +0x132\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(0x0)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:290 +0x9f\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00176a5a0)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3287 +0x33\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc002387238, 0xc0020bca80)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:165 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc0059d8ee0)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:279 +0x7b2\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc001ba8360)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:1013 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc00322e780, 0xc00167c900, 0xc0023878d0)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x825\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc006026b40, {0xc00322e880, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc006026b40)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb30\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc006026b40)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4c5\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc002387da8, 0xc002387d78)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:97 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc006026b40, 0xc001adcc00)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x4d3\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc000f58d20, 0xc0016e4090, 0xc001adcc00, {0xc003bd83f0, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x352\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc000f58d20, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x585\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
Jan 18 02:29:17 nomad[24428]: {"@level":"error","@message":"processing eval panicked scheduler - please report this as a bug!","@module":"worker.system_sched","@timestamp":"2025-01-18T02:29:17.189543Z","error":"runtime error: invalid memory address or nil pointer dereference","eval_id":"bcfb37b2-4735-b78b-2b5a-5cafbc3065b7","job_id":"m3hostfiles","namespace":"default","stack_trace":"goroutine 58 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:26 +0x5e\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58\npanic({0x2d99520?, 0x54eac00?})\n\truntime/panic.go:785 +0x132\ngithub.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(0x0)\n\tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:290 +0x9f\ngithub.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc00176a5a0)\n\tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3287 +0x33\ngithub.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc002387238, 0xc0020bca80)\n\tgithub.com/hashicorp/nomad/scheduler/preemption.go:165 +0x36\ngithub.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc0059d8ee0)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:279 +0x7b2\ngithub.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc001ba8360)\n\tgithub.com/hashicorp/nomad/scheduler/rank.go:1013 +0x28\ngithub.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc00322e780, 0xc00167c900, 0xc0023878d0)\n\tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x825\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc006026b40, {0xc00322e880, 0x3, 0xb?})\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc006026b40)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb30\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc006026b40)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4c5\ngithub.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc002387da8, 0xc002387d78)\n\tgithub.com/hashicorp/nomad/scheduler/util.go:97 +0x49\ngithub.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc006026b40, 0xc001adcc00)\n\tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x4d3\ngithub.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc000f58d20, 0xc0016e4090, 0xc001adcc00, {0xc003bd83f0, 0x24})\n\tgithub.com/hashicorp/nomad/nomad/worker.go:634 +0x352\ngithub.com/hashicorp/nomad/nomad.(*Worker).run(0xc000f58d20, 0x12a05f200)\n\tgithub.com/hashicorp/nomad/nomad/worker.go:463 +0x585\ncreated by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1\n\tgithub.com/hashicorp/nomad/nomad/worker.go:162 +0x59\n","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
Jan 18 02:29:17 nomad[24428]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2025-01-18T02:29:17.189679Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
Jan 18 02:29:17 nomad[24428]: {"@level":"error","@message":"error invoking scheduler","@module":"worker","@timestamp":"2025-01-18T02:29:17.189679Z","error":"failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference","worker_id":"8c760539-7b42-d176-4dc7-c6e7d716d04c"}
`

**Comment by tgross** [comment]
@morphine1900 as we've asked before, can you please provide a job specification that triggers the behavior and the API output for a node that should be eligible to receive that work.

**Comment by morphine1900** [comment]
It happens after we upgrade nomad. we leave 1 node from cluster, upgrade and join it back to the cluster.
From the log I can see nomad did a GC, tried to restart the old jobs then failed. It didn't fail on the same job so I assume it's not the spec's problem.

**Comment by tgross** [comment]
> It happens after we upgrade nomad. we leave 1 node from cluster, upgrade and join it back to the cluster.

From what version of Nomad were you upgrading? Can you provide the [Node API](https://developer.hashicorp.com/nomad/api-docs/nodes#read-node) output for that node.

> It didn't fail on the same job so I assume it's not the spec's problem.

Nevertheless, it can give us clues as to what code paths might be triggered.

**Comment by tgross** [comment]
Internal link: https://hashicorp.atlassian.net/browse/NET-12040
Also noting possible overlap with https://github.com/hashicorp/nomad/issues/20157

**Comment by Juanadelacuesta** [comment]
Hello @morphine1900, can you give us an update on this issue? Did you keep running into it? If you did, can you provide some information on your client configuration and the job or jobs you were running? In order to find the bug, we need to be able to reproduce the environment that triggers it, so having the client configuration and job specs gives us a good starting point.
Thank you!

**Comment by tgross** [comment]
I'm going to close this out as unresolved.
