### ISSUE TITLE
`Command+<Click>` on Job Name Opens Link in New and Current Tab

### ISSUE THREAD

**Issue by ChefAustin** [hashicorp/nomad#24277]
### Proposal
I'll be the first to admit that this is extremely nitpicky (hence why I filed this as a [extremely low-priority] FR instead of a Bug) but... When `Command+Click`'ing a job name link from the `/ui/jobs` view's table, it opens the job details view in both a new, non-active, tab ***and*** in the currently active tab.

Desired behavior is that the link only opens in a new, non-active tab.

This is merely a minor annoyance (but figured perhaps there is an easy fix ¯\\\_(ツ)_/¯).

**Device Details:**
macOS 14.7 (23H124)
Google Chrome v130.0.6723.70

### Use-cases
I often jump around between different jobs a lot so I like to keep the 'Jobs' view up and open each job details page in a new tab. So when I try to Minor annoyance: 

### Attempted Solutions
None but this can be worked-around by right-clicking the link and selecting 'Open Link in New Tab'.

**Comment by philrenaud** [comment]
Hey @ChefAustin, thanks for raising this. It should have been fixed in https://github.com/hashicorp/nomad/pull/23832 which should have gone out in Nomad 1.8.4. Can you confirm if you're beyond that version?

If so: being able to click the non-link part of the row is a "convenience" thing for people with poor mouse dexterity (and for whom landing on the link was a little tricky). I want to get this right; if I remove the event handler on the row itself, there's no possibility of a double-open, but it would also mean that the non-link part of the row is no longer clickable.

**Comment by ChefAustin** [comment]
_**D'oh!**_ I should've included that detail in my initial report (furthermore, I should've confirmed this bug still existed in latest release before filing).

As far as the non-link portion of the row, I'm less concerned with that (personally). It sounds like the fix applied in 1.8.4 release takes care of what I initially reported. Feel free to close this Issue.
