### ISSUE TITLE
interpolation failed in port_map

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/nomad#2680]
Meta value is not interpretable in `port_map`

### Nomad version
Nomad v0.5.1

### Reproduction steps

Here is the job file:
```
job "server-interpolation" {
  type = "service"
  datacenters = ["dc1"]
  update {
    stagger = "30s"
    max_parallel = 1
  }
  group "server-interpolation-group" {
    count = 1
    task "server" {
      meta {
        TCP_PORT = 40000
      }
      service {
        name = "server-interpolation"
        port = "http"
      }
      driver = "docker"
      config {
        image = "titan/server:0.0.1"
        port_map = {
          # OK
          # http = "40000"
          # FAIL
          http = "${NOMAD_META_TCP_PORT}"
        }
      }
      resources {
        cpu = 40
        memory = 50
        network {
          mbits = 1
          port "http" {
          }
        }
      }
    }
  }
}
```
After job is scheduled,  I got this error:

```
Task "simple-server" is "dead"
Task Resources
CPU     Memory  Disk  IOPS  Addresses
40 MHz  50 MiB  0 B   0     http: 10.0.1.10:47364

Recent Events:
Time                   Type            Description
05/26/17 15:28:06 CST  Not Restarting  Error was unrecoverable
05/26/17 15:28:06 CST  Driver Failure  failed to initialize task "server" for alloc "e4a027f4-35e4-4bc0-d4f6-2d8d0429a142": 1 error(s) decoding:

* cannot parse 'port_map[0][http]' as int: strconv.ParseInt: parsing "${NOMAD_META_TCP_PORT}": invalid syntax
05/26/17 15:28:06 CST  Received        Task received by client
```

**Comment by dadgar** [comment]
Hey,

This is fixed in  newer versions of Nomad. Can you please upgrade to 0.5.6!

Here is where we  interpolate: https://github.com/hashicorp/nomad/blob/master/client/driver/docker.go#L234-L239

Thanks,
Alex

**Comment by waterdudu** [comment]
Hi @dadgar 

I updated nomad to 0.5.6 today, the job still failed with the same error.

`* cannot parse 'port_map[0][http]' as int: strconv.ParseInt: parsing "${NOMAD_META_TCP_PORT}": invalid syntax
`

**Comment by dadgar** [comment]
Hey @waterdudu sorry for closing while it was a real issue! Put out a PR that should fix this and will be in 0.6.0!

Thanks,
Alex

**Comment by waterdudu** [comment]
Thanks @dadgar looking forward for new release!
