### ISSUE TITLE
Cluster experiencing segmentation violation across all servers

### ISSUE THREAD

**Issue by mdcollins05** [hashicorp/nomad#5241]
One of our clusters is experiencing a segmentation violation across all 3 of the servers. It seems that when the server attempts to become the leader, it panics and exits. One of the remaining servers then becomes the new leader and does the same.

We've tried shutting down all the servers at the same time and bringing them back up but we see the same error.

Additionally, we've tried stopping one server, clearing the contents of `/var/lib/nomad/server/` and restarting the server with the same results.

The 2 listed eval IDs are consistent across all 3 servers and between each run.

Logs entries:
```
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:     2019/01/25 03:36:48 [ERR] state_store: unable to find eval id "a11e035b-30ad-d978-9102-e1afe3b28e50"
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:     2019/01/25 03:36:48 [ERR] nomad.fsm: ApplyPlan failed: unable to find eval id "a11e035b-30ad-d978-9102-e1afe3b28e50"
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:     2019/01/25 03:36:48 [ERR] state_store: unable to find eval id "5df1c6bb-4551-1817-7390-2bc8d61c0f93"
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:     2019/01/25 03:36:48 [ERR] nomad.fsm: ApplyPlan failed: unable to find eval id "5df1c6bb-4551-1817-7390-2bc8d61c0f93"
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:     2019/01/25 03:36:48 [ERR] state_store: unable to find eval id "a11e035b-30ad-d978-9102-e1afe3b28e50"
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:     2019/01/25 03:36:48 [ERR] nomad.fsm: ApplyPlan failed: unable to find eval id "a11e035b-30ad-d978-9102-e1afe3b28e50"
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xf01665]
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: goroutine 182 [running]:
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computePlacements(0xc424196d20, 0x2bb8aa0, 0x0, 0x0, 0xc420484cc0, 0x2, 0x2, 0xc42430bec0,
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:504 +0xb55
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computeJobAllocs(0xc424196d20, 0xc421239a00, 0xc42430bd40)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:410 +0x1586
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/scheduler.(*GenericScheduler).process(0xc424196d20, 0x1d, 0xc424c45cf0, 0x7)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:245 +0x471
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/scheduler.(*GenericScheduler).(github.com/hashicorp/nomad/scheduler.process)-fm(0xc424b81750, 0x0, 0x0)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:144 +0x2a
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc424b818b0, 0xc424b818c0, 0xc, 0xffffffffffffffff)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/scheduler/util.go:271 +0x43
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process(0xc424196d20, 0xc420e746e0, 0xc42057ac80, 0x1d7cde0)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:144 +0x123
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/nomad.(*nomadFSM).reconcileQueuedAllocations(0xc4205d0ba0, 0x284bfb, 0x0, 0x0)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:1383 +0x8ed
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/nomad.(*nomadFSM).applyReconcileSummaries(0xc4205d0ba0, 0xc424cf2081, 0x8, 0x8, 0x284bfb, 0xc424b81f76, 0x2b96de0)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:758 +0x7e
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc4205d0ba0, 0xc420856ab0, 0x2b96de0, 0x3)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:210 +0x6f1
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc42538e8f0)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:57 +0x15a
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc4205aa000)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:120 +0x2fa
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.runFSM)-fm()
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/api.go:506 +0x2a
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc4205aa000, 0xc420177fc0)
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:146 +0x53
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]: created by github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Jan 25 03:36:48 prod-nomadusw1-server03 nomad[29777]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:144 +0x66
```

One more interesting, error message from a host within the cluster:
`Jan 25 02:57:08 *prod-nomadusw1-server01* nomad[32217]:     2019/01/25 02:57:08 [ERR] memberlist: Failed push/pull merge: Node '*prod-nomadusw1-server02*.us-west-1' protocol version (0) is incompatible: [1, 5] from=*prod-nomadusw1-server02*:39462`

Nomad version: 
```
$ nomad --version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
```

**Comment by nickethier** [comment]
Hey @mdcollins05 

At first glance I believe you're hitting a bug that was fixed in Nomad 0.8.5: https://github.com/hashicorp/nomad/commit/82304f93b37a0806f95d1527f141c5c0c71c52ed

I can try swapping the server binary out for an updated one and start it up. I would recommend running our latest release 0.8.7

**Comment by mdcollins05** [comment]
Heya @nickethier 

Thanks for the quick response!

We've upgraded all 3 servers in the cluster to version 0.8.7 and we are still seeing the same behavior and the error message hasn't changed.

Any other thoughts?

**Comment by nickethier** [comment]
Looks like we ended up with a very unusual state where a placement was marked as a canary but there was no corresponding deployment?!

I had @mdcollins05 apply this patch which stopped the panics from occurring: https://github.com/hashicorp/nomad/compare/v0.8.7...b-scheduler-npe.patch

We'll make sure this makes it into the upcoming 0.9 release!
