### ISSUE TITLE
Alloc log viewer UI no longer shows all content

### ISSUE THREAD

**Issue by inf0rmer** [hashicorp/nomad#6098]
### Nomad version
0.9.4

### Operating system and Environment details
Mac OS 10.14.6
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

### Issue
Alloc log viewer UI no longer shows all content

### Reproduction steps
- In the Nomad UI, visit the page for an allocation's logs (ie. `ui/allocations/ALLOC_UUID/JOB/logs`
- The log viewer no longer shows the buttons on the right-hand side for Head/Tail/Pause
- The full content of the logs is no longer shown because it is impossible to horizontally scroll

**Comment by inf0rmer** [comment]
After investigating this issue seems to have been introduced by [this change](https://github.com/hashicorp/nomad/commit/dca386ca704ce6ffedbc98fbfa27083017e6e462#diff-45559625b92aed273ebab4861613d758)

**Comment by derzufall** [comment]
Having this problem aswell and it's really annoying because nobody can read the task's logs anymore for the the last 2 micro versions.

Currently the log lines just extend beyond the window borders. You can't even scroll to read the rest, aber the top right buttons also disappear beyond the screen.

**Comment by DingoEatingFuzz** [comment]
This is fixed on master and will be released in v0. 10.0 and backported to v0.9.6.

Thank you for reporting!

**Comment by derzufall** [comment]
Actually this bug still persists in v0.9.6.
We updated all our infrastructure to the new Version because we use the log viewer a lot.

Status-Quo has not changed with 0.9.6.
* The log-area flows out of the screen to the right hand side.
* The log viewer no longer shows the buttons on the right-hand side for Head/Tail/Pause
* The full content of the logs is no longer shown because it is impossible to horizontally scroll

**Comment by DingoEatingFuzz** [comment]
Hi @derzufall, sorry you're still experiencing this bug (which I know from first-hand experience is super annoying).

I just downloaded a clean copy of v0.9.6 to see if I could reproduce this, but I got horizontal scrolling:

![image](https://user-images.githubusercontent.com/174740/66507032-4aea5f80-ea83-11e9-8b95-3e3bb556543a.png)

Could the old UI be cached in your browser? Or maybe cached in a proxy? Can you reproduce this in an isolated nomad installation?

**Comment by shantanugadgil** [comment]
Maybe a "full refresh" of the browser might help? CTRL+F5
?

**Comment by derzufall** [comment]
Hi @DingoEatingFuzz,
we use Firefox as a corporate browser. After realizing that nobody uses anything except Chrome I checked with Chrome and the issue was gone indeed.

However the issue still exists with Firefox. Can you verify that?
We dont use any caching or proxying whatsoever.

Regards
Zufall

**Comment by DingoEatingFuzz** [comment]
Uuuggghhhh, I confirmed that this behaves as you reported in Firefox 😞

I was promised rendering engines that all behaved the same way. This wasn't supposed to be a problem in the 2010s!! _*shakes fist*_
