### ISSUE TITLE
Nomad: missing docker driver

### ISSUE THREAD

**Issue by let4be** [hashicorp/nomad#780]
Nomad does not detect docker driver sometimes,
supposedly when nomad started BEFORE docker daemon
`Constraint "missing drivers" filtered 3 nodes`

**Comment by dadgar** [comment]
This has been fixed in master and will be in Nomad 0.3. The fix was to have the fingerprinters that detect docker run periodically. So the Nomad client will detect the new docker instance in < 1 min after it is started.

**Comment by ErikEvenson** [comment]
I'm still getting this problem.  What specifically does nomad use to fingerprint the availability of docker?

**Comment by ErikEvenson** [comment]
@diptanu I found out that I was trying to execute a nomad command with a user that was not in the docker group.  So if you reopened this for me, you should probably close it again.  Thanks.

**Comment by isereb** [comment]
1) Make sure your user in docker group or sudo
2) Make sure your docker daemon is up
